<?php
  exit;
?>
[FromAddress]
0=administrator
1=mail delivery
2=mailer-daemon
3=mx1
4=mx2
5=postmaster
6=yahoo! groups
7=microsoft exchange
[Subject]
0=bermittlungsstatus (fehlgeschlagen)
1=delivery failure
2=delivery has failed
3=delivery status
4=failure notice
5=mail delivery failed
6=mail system error
7=mail-system-fehler
8=mailzustellung fehlgeschlagen
9=non delivery
10=returned mail
11=undeliverable
12=undelivered
13=user unknown
14=zurückgeschickte mail:
15=unzustellbar
16=unable to process your message
[MailBody]
0=account has been disabled
1=account inactive
2=account is not allowed
3=address rejected by host
4=address* unknown
5=bad address syntax
6=bad q data format in dns response
7=cannot be delivered
8=cannot check
9=client host rejected
10=connection refused
11=connection timed out
12=could not be delivered
13=couldn't find any host named
14=deferred:
15=delivery*failed
16=der server konnte ihre nachricht nicht an folgende adressen zustellen
17=destination addresses were unknown
18=destination computer not found
19=disabled
20=dns for host*is misconfigured
21=dns server failure
22=does not exist
23=does not like recipient
24=domain name system has no information
25=domain name unknown
26=email name is not found
27=empfaenger unbekannt oder nicht erreichbar
28=expired
29=failed
30=had permanent fatal errors
31=host name is unknown
32=host not found
33=host unknown
34=host*not found
35=host*said
36=inactive user
37=incorrect address format
38=invalid final delivery userid
39=invalid recipient
40=is not a valid mailbox
41=is not accepting any mail
42=mailbox doesn't exist
43=mailbox not found
44=mailbox unavailable
45=name service error for domain
46=no dns a-data returned
47=no mailbox
48=no mailbox here by that name
49=no matches to nameserver query
50=no response
51=no smtp prompt at the host
52=no such user
53=nondeliverable
54=not a valid mailbox
55=not a valid*user
56=not allowed
57=not listed
58=not our customer
59=not recognized
60=permission denied
61=recipient address denied
62=recipient address rejected
63=recipient name is not recognized
64=relay access denied
65=relaying denied
66=relaying messages to*is not allowed
67=requested action not taken: mailbox unavailable
68=service unavailable
69=sorry, no mailbox here by that name
70=sorry, that
71=suspended
72=teilnehmer existiert nicht
73=the recipient name is not recognized
74=the user's email name is not found
75=this account has been disabled or discontinued
76=this account is disabled
77=this address no longer accepts mail
78=this user doesn't have a * account
79=übermittlung an folgende empfänger fehlgeschlagen*
80=unable to relay
81=unable to take delivery
82=undeliverable
83=undelivered
84=unknown host
85=unknown local*part
86=unknown or illegal alias
87=unknown user
88=user account inactive
89=user account not activated
90=user*does not exist
91=user*doesn't have a account
92=user*not found
93=user*not known
94=user*not listed
95=user*not listed in public name & address book
96=user*unknown
97=was not delivered to
98=Domino Verzeichnis
99=not listed in Domino Directory
100=we are unable to process the message
101=besitzt keine E-Mail-Adresse
102=550 Protocol violation
103=unrouteable address
104=Your message did not reach some or all of the intended recipients
105=RESOLVER.ADR.RecipNotFound
[TextNotInMailBody]
0=exhausted allowed storage
1=is currently not permitted to
2=mailbox full
3=mailbox voll
4=over quota
5=quota exceeded
6=speichervolumen ueberschritten
7=User has too many messages on the server
