/*
#############################################################################
#                SuperMailingList / SuperWebMailer                          #
#               Copyright © 2007 - 2017 Mirko Boeer                         #
#                    Alle Rechte vorbehalten.                               #
#                http://www.supermailinglist.de/                            #
#                http://www.superwebmailer.de/                              #
#   Support SuperMailingList: support@supermailinglist.de                   #
#   Support SuperWebMailer: support@superwebmailer.de                       #
#   Support-Forum: http://board.superscripte.de/                            #
#                                                                           #
#   Dieses Script ist urheberrechtlich geschuetzt. Zur Nutzung des Scripts  #
#   muss eine Lizenz erworben werden.                                       #
#                                                                           #
#   Das Script darf weder als ganzes oder als Teil eines anderen Projekts   #
#   verwendet oder weiterverkauft werden.                                   #
#                                                                           #
#   Beachten Sie fuer den Einsatz des Script-Pakets die Lizenzbedingungen   #
#                                                                           #
#   Fuehren Sie keine Veraenderungen an diesem Script durch. Jegliche       #
#   Veraenderungen koennen nicht supported werden.                          #
#                                                                           #
#############################################################################
*/

CKEDITOR.editorConfig=function(d){d.filebrowserImageBrowseUrl=CKEDITOR.basePath+"filemanager/index.php?type=Images";d.filebrowserImageUploadUrl=CKEDITOR.basePath+"filemanager/connectors/php/upload.php?type=Images&command=QuickUpload";d.filebrowserDocPropsBrowseUrl=CKEDITOR.basePath+"filemanager/index.php?type=Images";d.uiColor="#E2EAF3";d.title=!1;d.browserContextMenuOnCtrl=!1;CKEDITOR.disableAutoInline=!0;d.fullPage=!0;d.allowedContent=!0;d.docType="<!DOCTYPE HTML>";d.emailProtection="";d.enterMode=
CKEDITOR.ENTER_DIV;d.fillEmptyBlocks=!0;d.fontSize_sizes="8pt/ 8pt;9pt/ 9pt;10pt/10pt;11pt/11pt;12pt/12pt;14pt/14pt;18pt/18pt;24pt/24pt;36pt/36pt/8px/ 8px;9px/ 9px;10px/10px;11px/11px;12px/12px;14px/14px;16px/16px;18px/18px;20px/20px;22px/22px;24px/24px;26px/26px;28px/28px;36px/36px;48px/48px;72px/72px";d.font_names="Arial;Calibri;Comic Sans MS;Courier New;Georgia;Tahoma;Times New Roman;Verdana";d.ignoreEmptyParagraph=!0;d.removeDialogTabs+=";image:advanced";d.disableNativeTableHandles=!0;d.disableObjectResizing=
!1;d.toolbar_MyDefaultToolbar=[{name:"document",items:"Source - NewPage DocProps Preview Print - Templates".split(" ")},{name:"clipboard",items:"Cut Copy Paste PasteText PasteFromWord - Undo Redo".split(" ")},{name:"editing",items:"Find Replace - SelectAll - SpellChecker Scayt".split(" ")},"/",{name:"basicstyles",items:"Bold Italic Underline Strike Subscript Superscript - RemoveFormat".split(" ")},{name:"paragraph",items:"NumberedList BulletedList - Outdent Indent - Blockquote CreateDiv - JustifyLeft JustifyCenter JustifyRight JustifyBlock".split(" ")},
{name:"links",items:["Link","Unlink","Anchor"]},{name:"insert",items:"Image Table HorizontalRule Smiley SpecialChar PageBreak".split(" ")},"/",{name:"styles",items:["Styles","Format","Font","FontSize"]},{name:"colors",items:["TextColor","BGColor"]},{name:"tools",items:["Maximize","ShowBlocks","-","About"]},"/",{name:"newsletter",items:["placeholdercb","queryfunctionbtn","loadfilebtn","targetgroupsBtn"]}];d.toolbar_MyDefaultMailToolbar=[{name:"document",items:"Source - NewPage DocProps Preview Print - Templates".split(" ")},
{name:"clipboard",items:"Cut Copy Paste PasteText PasteFromWord - Undo Redo".split(" ")},{name:"editing",items:"Find Replace - SelectAll - SpellChecker Scayt".split(" ")},"/",{name:"basicstyles",items:"Bold Italic Underline Strike Subscript Superscript - RemoveFormat".split(" ")},{name:"paragraph",items:"NumberedList BulletedList - Outdent Indent - Blockquote CreateDiv - JustifyLeft JustifyCenter JustifyRight JustifyBlock".split(" ")},{name:"links",items:["Link","Unlink","Anchor"]},{name:"insert",
items:"Image Table HorizontalRule Smiley SpecialChar PageBreak".split(" ")},"/",{name:"styles",items:["Styles","Format","Font","FontSize"]},{name:"colors",items:["TextColor","BGColor"]},{name:"tools",items:["Maximize","ShowBlocks","-","About"]},"/",{name:"newsletter",items:"placeholdercb queryfunctionbtn textblocksbtn loadfilebtn smebarbtn targetgroupsBtn".split(" ")}];d.toolbar_MyDefaultSimpleToolbar=[{name:"document",items:"Source - NewPage DocProps Preview Print".split(" ")},{name:"clipboard",
items:"Cut Copy Paste PasteText PasteFromWord - Undo Redo".split(" ")},{name:"editing",items:"Find Replace - SelectAll - SpellChecker Scayt".split(" ")},"/",{name:"basicstyles",items:"Bold Italic Underline Strike Subscript Superscript - RemoveFormat".split(" ")},{name:"paragraph",items:"NumberedList BulletedList - Outdent Indent - Blockquote CreateDiv - JustifyLeft JustifyCenter JustifyRight JustifyBlock".split(" ")},{name:"links",items:["Link","Unlink"]},{name:"insert",items:"Image Table HorizontalRule Smiley SpecialChar PageBreak".split(" ")},
"/",{name:"styles",items:["Styles","Format","Font","FontSize"]},{name:"colors",items:["TextColor","BGColor"]},{name:"tools",items:["Maximize","ShowBlocks","-","About"]},"/",{name:"newsletter",items:["loadfilebtn"]}];d.toolbar_MyDefaultReadOnlyToolbar=[{name:"default",items:"Preview Print Find Maximize - About".split(" ")}];d.toolbar_MyDefaultMultiLineToolbar=[{name:"document",items:["Source","-"]},{name:"clipboard",items:"Cut Copy Paste PasteText PasteFromWord - Undo Redo".split(" ")},{name:"editing",
items:"Find Replace - SelectAll - SpellChecker Scayt".split(" ")},"/",{name:"basicstyles",items:"Bold Italic Underline Strike Subscript Superscript - RemoveFormat".split(" ")},{name:"paragraph",items:"NumberedList BulletedList - Outdent Indent - Blockquote CreateDiv - JustifyLeft JustifyCenter JustifyRight JustifyBlock".split(" ")},{name:"links",items:["Link","Unlink","Anchor"]},{name:"insert",items:"Image Table HorizontalRule Smiley SpecialChar PageBreak".split(" ")},"/",{name:"styles",items:["Styles",
"Format","Font","FontSize"]},{name:"colors",items:["TextColor","BGColor"]},"/",{name:"newsletter",items:["placeholdercb","queryfunctionbtn","textblocksbtn","targetgroupsBtn"]}];var a=CKEDITOR.basePath;a=a.substr(0,a.indexOf("ckeditor/"))+"plugins/";CKEDITOR.plugins.addExternal("queryfunctionbtn",a+"ckeditorplugins/queryfunctionbtn/","plugin.js");CKEDITOR.plugins.addExternal("textblocksbtn",a+"ckeditorplugins/textblocksbtn/","plugin.js");CKEDITOR.plugins.addExternal("loadfilebtn",a+"ckeditorplugins/loadfilebtn/",
"plugin.js");CKEDITOR.plugins.addExternal("placeholdercb",a+"ckeditorplugins/placeholdercb/","plugin.js");CKEDITOR.plugins.addExternal("smebarbtn",a+"ckeditorplugins/smebarbtn/","plugin.js");CKEDITOR.plugins.addExternal("targetgroups",a+"ckeditorplugins/targetgroups/","plugin.js");CKEDITOR.plugins.addExternal("docprops",a+"ckeditorplugins/docprops/","plugin.js");CKEDITOR.plugins.addExternal("tableresize",a+"ckeditorplugins/tableresize/","plugin.js");CKEDITOR.plugins.addExternal("codemirror",a+"ckeditorplugins/codemirror/",
"plugin.js");a="docprops,placeholdercb,queryfunctionbtn,textblocksbtn,loadfilebtn,smebarbtn,tableresize,codemirror";document.getElementById("TargetGroupsSupport")&&"1"==document.getElementById("TargetGroupsSupport").value&&(a+=",targetgroups");d.extraPlugins=a;d.templates_files=[CKEDITOR.basePath.substr(0,CKEDITOR.basePath.indexOf("ckeditor/"))+"fcktemplates.php"];d.resize_enabled=!1;d.toolbarCanCollapse=!0;d.scayt_autoStartup=!1;d.removePlugins="elementspath,magicline";CKEDITOR.config.fullPage&&
(d.removePlugins+=",tableselection")};
CKEDITOR.on("instanceReady",function(d){var a=d.editor.element,c=a.$.form&&new CKEDITOR.dom.element(a.$.form);if(c){var b=function(){d.editor.dataProcessor.writer.indentationChars="";d.editor.dataProcessor.writer.lineBreakChars="";d.editor.updateElement()};a=d.editor.dataProcessor;SetHTMLFilterRules(a&&a.htmlFilter);c.on("submit",b);c.$.submit.nodeName||c.$.submit.length||(c.$.submit=CKEDITOR.tools.override(c.$.submit,function(a){return function(){d.editor.updateElement();a.apply?a.apply(this,arguments):
a()}}));d.editor.on("destroy",function(){c.removeListener("submit",b)})}d.editor.dataProcessor.writer.indentationChars="    ";d.editor.dataProcessor.writer.selfClosingEnd=" />";a="div p table td tr ol ul li h1 h2 h3 h4 h5 h6".split(" ");for(var g in a)d.editor.dataProcessor.writer.setRules(a[g],{indent:!0,breakBeforeOpen:!0,breakAfterOpen:!1,breakBeforeClose:!1,breakAfterClose:!0});d.editor.dataProcessor.writer.setRules("head",{indent:!0,breakBeforeOpen:!1,breakAfterOpen:!0,breakBeforeClose:!0,breakAfterClose:!0});
d.editor.dataProcessor.writer.setRules("title",{indent:!0,breakBeforeOpen:!0,breakAfterOpen:!1,breakBeforeClose:!1,breakAfterClose:!0});d.editor.dataProcessor.writer.setRules("body",{indent:!0,breakBeforeOpen:!0,breakAfterOpen:!0,breakBeforeClose:!0,breakAfterClose:!1});d.editor.dataProcessor.writer.setRules("meta",{indent:!0,breakBeforeOpen:!0,breakAfterOpen:!0,breakBeforeClose:!0,breakAfterClose:!0});d.editor.dataProcessor.writer.setRules("style",{indent:!0,breakBeforeOpen:!0,breakAfterOpen:!0,
breakBeforeClose:!0,breakAfterClose:!0});d.editor.dataProcessor.writer.setRules("br",{indent:!1,breakBeforeOpen:!1,breakAfterOpen:!1,breakBeforeClose:!1,breakAfterClose:!1})});
function SetHTMLFilterRules(d){d.addRules({elements:{$:function(a){var c,b,d;if("img"==a.name&&(c=a.attributes.style)){var f=(b=/(?:^|\s)width\s*:\s*(\d+)px/i.exec(c))&&b[1];var e=(b=/(?:^|\s)height\s*:\s*(\d+)px/i.exec(c))&&b[1];(c=(b=/(?:^|\s)float\s*:\s*(\w*)(;|$)/i.exec(c))&&b[1])&&(c=c.replace(/;/,""));"right"!=c&&"left"!=c&&(afload=!1);f&&(a.attributes.style=a.attributes.style.replace(/(?:^|\s)width\s*:\s*(\d+)px;?/i,""),a.attributes.width=f);e&&(a.attributes.style=a.attributes.style.replace(/(?:^|\s)height\s*:\s*(\d+)px;?/i,
""),a.attributes.height=e);c&&(a.attributes.style=a.attributes.style.replace(/(?:^|\s)float\s*:\s*(\w*);?/i,""),a.attributes.align=c)}if("p"==a.name||"div"==a.name||"td"==a.name)if(""==a.attributes.background&&delete a.attributes.background,c=a.attributes.style)(e=(b=/(?:^|\s)text-align\s*:\s*(\w*)(;|$)/i.exec(c))&&b[1])&&(e=e.replace(/;/,"")),(c=(b=/(?:^|\s)vertical-align\s*:\s*(\w*)(;|$)/i.exec(c))&&b[1])&&(c=c.replace(/;/,"")),e&&(a.attributes.align=e),c&&(a.attributes.valign=c);if("img"==a.name&&
(c=a.attributes.style)){(e=(b=/(?:^|\s)margin\s*:\s*(.*)(;|$)/i.exec(c))&&b[1])&&(e=e.replace(/;/,""));e&&(a.attributes.style=a.attributes.style.replace(/(?:^|\s)margin\s*:\s*(.*)(;|$)/i,""),e=e.trim(),-1!=e.indexOf(" ")?(b=parseInt(e),e=parseInt(e.substr(e.indexOf(" ")+1)),a.attributes.hspace=e,a.attributes.vspace=b):0<parseInt(e)&&(a.attributes.hspace=parseInt(e),a.attributes.vspace=parseInt(e)));(e=(b=/(?:^|\s)margin-left\s*:\s*(\d+)px/i.exec(c))&&b[1]&&0<=parseInt(b[1]))&&(e=parseInt(b[1]));(f=
(b=/(?:^|\s)margin-right\s*:\s*(\d+)px/i.exec(c))&&b[1]&&0<=parseInt(b[1]))&&(f=parseInt(b[1]));var h=(b=/(?:^|\s)margin-top\s*:\s*(\d+)px/i.exec(c))&&b[1]&&0<=parseInt(b[1]);h&&(h=parseInt(b[1]));(d=(b=/(?:^|\s)margin-bottom\s*:\s*(\d+)px/i.exec(c))&&b[1]&&0<=parseInt(b[1]))&&(d=parseInt(b[1]));e&&f&&e==f&&(a.attributes.hspace=e,a.attributes.style=a.attributes.style.replace(/(?:^|\s)margin-left\s*:\s*(\d+)px(;|$)/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)margin-right\s*:\s*(\d+)px(;|$)/i,
""));h&&d&&h==d&&(a.attributes.vspace=h,a.attributes.style=a.attributes.style.replace(/(?:^|\s)margin-top\s*:\s*(\d+)px(;|$)/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)margin-bottom\s*:\s*(\d+)px(;|$)/i,""));(e=(b=/(?:^|\s)border-width\s*:\s*(\d+)px/i.exec(c))&&b[1]&&0<=parseInt(b[1]))&&(e=parseInt(b[1]));(f=(b=/(?:^|\s)border-style\s*:\s*(\w*)(;|$)/i.exec(c))&&b[1])&&(f=f.replace(/;/,""));(h=(b=/(?:^|\s)border-bottom\s*:\s*(\S*)\s*solid/i.exec(c))&&b[1]&&-1!=b[0].indexOf("solid")&&
0<=parseInt(b[1]))&&(h=parseInt(b[1]));(d=(b=/(?:^|\s)border-left\s*:\s*(\S*)\s*solid/i.exec(c))&&b[1]&&-1!=b[0].indexOf("solid")&&0<=parseInt(b[1]))&&(d=parseInt(b[1]));var k=(b=/(?:^|\s)border-right\s*:\s*(\S*)\s*solid/i.exec(c))&&b[1]&&-1!=b[0].indexOf("solid")&&0<=parseInt(b[1]);k&&(k=parseInt(b[1]));var l=(b=/(?:^|\s)border-top\s*:\s*(\S*)\s*solid/i.exec(c))&&b[1]&&-1!=b[0].indexOf("solid")&&0<=parseInt(b[1]);l&&(l=parseInt(b[1]));if(h&&d&&k&&l){d=[h,d,k,l];b=d[0];for(k=1;k<d.length;k++)if(b!=
d[k]){b=-1;break}-1!=b&&(e=String(parseInt(h)),f="solid")}(l=(b=/(?:^|\s)border-top-width\s*:\s*(\d+)px/i.exec(c))&&b[1]&&0<=parseInt(b[1]))&&(l=parseInt(b[1]));(k=(b=/(?:^|\s)border-right-width\s*:\s*(\d+)px/i.exec(c))&&b[1]&&0<=parseInt(b[1]))&&(k=parseInt(b[1]));(d=(b=/(?:^|\s)border-left-width\s*:\s*(\d+)px/i.exec(c))&&b[1]&&0<=parseInt(b[1]))&&(d=parseInt(b[1]));(h=(b=/(?:^|\s)border-bottom-width\s*:\s*(\d+)px/i.exec(c))&&b[1]&&0<=parseInt(b[1]))&&(h=parseInt(b[1]));var m=(b=/(?:^|\s)border-top-style\s*:\s*(\w*)(;|$)/i.exec(c))&&
b[1]&&-1!=b[1].lastIndexOf("solid"),n=(b=/(?:^|\s)border-right-style\s*:\s*(\w*)(;|$)/i.exec(c))&&b[1]&&-1!=b[1].lastIndexOf("solid"),p=(b=/(?:^|\s)border-left-style\s*:\s*(\w*)(;|$)/i.exec(c))&&b[1]&&-1!=b[1].lastIndexOf("solid");c=(b=/(?:^|\s)border-bottom-style\s*:\s*(\w*)(;|$)/i.exec(c))&&b[1]&&-1!=b[1].lastIndexOf("solid");m&&n&&p&&c&&(f="solid");if(h&&d&&k&&l){d=[h,d,k,l];b=d[0];for(k=1;k<d.length;k++)if(b!=d[k]){b=-1;break}-1!=b&&(e=String(parseInt(h)))}0<=e&&"solid"==f&&(a.attributes.style=
a.attributes.style.replace(/(?:^|\s)border-width\s*:\s*(\d+)px?/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-style\s*:\s*(\w*)(;|$)?/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-bottom\s*:\s*(\S*)\s*solid(;|$)/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-left\s*:\s*(\S*)\s*solid(;|$)/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-right\s*:\s*(\S*)\s*solid(;|$)/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-top\s*:\s*(\S*)\s*solid(;|$)/i,
""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-top-width\s*:\s*(\d+)px(;|$)/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-right-width\s*:\s*(\d+)px(;|$)/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-left-width\s*:\s*(\d+)px(;|$)/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-bottom-width\s*:\s*(\d+)px(;|$)/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-top-style\s*:\s*(\w*)(;|$)/i,""),a.attributes.style=
a.attributes.style.replace(/(?:^|\s)border-right-style\s*:\s*(\w*)(;|$)/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-left-style\s*:\s*(\w*)(;|$)/i,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)border-bottom-style\s*:\s*(\w*)(;|$)/i,""),a.attributes.border=parseInt(e))}if("table"==a.name||"td"==a.name)if(a.attributes.align&&"middle"==a.attributes.align&&(a.attributes.align="center"),""==a.attributes.background&&delete a.attributes.background,c=a.attributes.style){c=
convertRGBToHex(c);a.attributes.style=c;(f=(b=/(?:^|\s)width\s*:\s*(\S*)?/i.exec(c))&&b[1])&&-1==f.indexOf("%")&&(f=parseInt(f));(e=(b=/(?:^|\s)height\s*:\s*(\S*)?/i.exec(c))&&b[1])&&-1==e.indexOf("%")&&(e=parseInt(e));f&&(f=String(f).replace(/;/,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)width\s*:\s*(\S*)?/i,""),a.attributes.width=f);e&&(e=String(e).replace(/;/,""),a.attributes.style=a.attributes.style.replace(/(?:^|\s)height\s*:\s*(\S*)?/i,""),a.attributes.height=e);if(b=(b=/(?:^|\s)background-color\s*:\s*(\S*)(;|$)/i.exec(c))&&
b[1])b=b.replace(/;/,""),a.attributes.bgcolor=b;(c=(b=/(?:^|\s)white-space\s*:\s*(\S*)(;|$)/i.exec(c))&&b[1])&&(c=c.replace(/;/,""));"nowrap"!=c&&(c=!1);c&&(a.attributes.style=a.attributes.style.replace(/(?:^|\s)white-space\s*:\s*(\S*)(;|$)?/i,""),a.attributes.nowrap="nowrap")}"body"==a.name&&(c=a.attributes.style)&&(c=convertRGBToHex(c),a.attributes.style=c,b=(b=/(?:^|\s)background-color\s*:\s*(\S*)(;|$)/i.exec(c))&&b[1])&&(b=b.replace(/;/,""),a.attributes.bgcolor=b);a.attributes.style&&""!=a.attributes.style.replace(/ /,
"")&&";"!=a.attributes.style.replace(/ /,"")?(c=a.attributes.style,-1!=c.indexOf("url(&quot;")&&(c=c.replace("url(&quot;","url('"),c=c.replace("&quot;)","')"),a.attributes.style=c)):delete a.attributes.style;return a}},attributes:{style:function(a,c){return convertRGBToHex(a)}}})}
CKEDITOR.on("dialogDefinition",function(d){var a=d.data.name,c=d.data.definition,b=d.data.definition.dialog;if("link"==a){var g=c.getContents("info");var f=GetPlaceholdersForLinkDialog(d.editor);0<f.length&&g.add({type:"select",label:d.editor.lang.placeholdercb.cbSerialEMailFieldAsURLLabel,id:"cbSerialEMailFieldAsURL",items:[[d.editor.lang.placeholdercb.cbSerialEMailFieldAsURLSelect,0]].concat(f),css:[CKEDITOR.config.contentsCss,CKEDITOR.getUrl(CKEDITOR.skinPath+"editor.css")],"default":"0",onChange:function(){InsertSerialFieldValueInLinkField("cbSerialEMailFieldAsURL",
"url")}});g=g.get("linkType");var e=g.onChange;g.onChange=function(){var a;"url"!=CKEDITOR.dialog.getCurrent().getValueOf("info","linkType")?(a=CKEDITOR.dialog.getCurrent().getContentElement("info","cbSerialEMailFieldAsURL"))&&a.disable():(a=CKEDITOR.dialog.getCurrent().getContentElement("info","cbSerialEMailFieldAsURL"))&&a.enable();e.apply?e.apply(this):e()}}if("image"==a){g=c.getContents("info");g.add({type:"checkbox",label:d.editor.lang.placeholdercb.chkboxInsertImageAsURL,id:"chkInsertImageAsCompleteURL",
css:[CKEDITOR.config.contentsCss,CKEDITOR.getUrl(CKEDITOR.skinPath+"editor.css")],onClick:function(){SetImageAsCompleteURL("chkInsertImageAsCompleteURL")}},"txtAlt");g.get("txtBorder")["default"]="0";d=g.get("txtUrl");var h=d.onChange;d.onChange=function(){RefreshImageAsCompleteURL();h.apply?h.apply(this):h()};c.getContents("Link").remove("browse")}"docProps"==a&&(c.removeContents("general"),c.removeContents("preview"),c=c.getContents("design"),c.remove("bgFixed"),c.get("bgImage").style="width: 210px",
c.get("bgImageChoose").style="display:inline-block;margin-top:10px;margin-left: 10px");if("tableProperties"==a)b.on("show",function(){var a=CKEDITOR.currentInstance.getSelection(),b;if(a&&(b=a.getStartElement()&&a.getStartElement().getAscendant("table",!0))){a=CKEDITOR.dialog.getCurrent().getContentElement("info","txtWidth");var c=CKEDITOR.dialog.getCurrent().getContentElement("info","txtHeight"),d=b.getStyle("width",""),e=b.getStyle("height","");!d&&a&&(b.setStyle("width",b.getAttribute("width")+
"px"),a.setValue(b.getAttribute("width"),!0),a.onChange());!e&&c&&(b.setStyle("height",b.getAttribute("height")+"px"),c.setValue(b.getAttribute("height"),!0),c.onChange())}})});function RefreshImageAsCompleteURL(){CKEDITOR.dialog.getCurrent().setValueOf("info","chkInsertImageAsCompleteURL",-1<CKEDITOR.dialog.getCurrent().getValueOf("info","txtUrl").indexOf("http://")||-1<CKEDITOR.dialog.getCurrent().getValueOf("info","txtUrl").indexOf("https://"))}
function SetImageAsCompleteURL(d){d=CKEDITOR.dialog.getCurrent().getValueOf("info",d);var a=CKEDITOR.dialog.getCurrent().getValueOf("info","txtUrl"),c=CKEDITOR.basePath;c=c.substr(0,c.indexOf("/ckeditor"));for(var b=0,g=c;-1!=g.lastIndexOf("/");)g=g.substr(0,g.lastIndexOf("/")),b++;if(2<b)for(g=0;g<b-2;g++)c=c.substr(0,c.lastIndexOf("/"));if(d)-1==a.indexOf("http:")&&-1==a.indexOf("https:")&&(a=c+a,CKEDITOR.dialog.getCurrent().setValueOf("info","txtUrl",a));else if(-1<a.indexOf("http:")||-1<a.indexOf("https:"))a=
a.substr(c.length),CKEDITOR.dialog.getCurrent().setValueOf("info","txtUrl",a)}
function InsertSerialFieldValueInLinkField(d,a){if("anchor"!=CKEDITOR.dialog.getCurrent().getValueOf("info","linkType")){var c=CKEDITOR.dialog.getCurrent().getValueOf("info",d);if(0!=c){var b=CKEDITOR.dialog.getCurrent().getValueOf("info",a);b=0>c.indexOf("Link")?b+c:c;CKEDITOR.dialog.getCurrent().setValueOf("info",a,b);CKEDITOR.dialog.getCurrent().setValueOf("info",d,0);CKEDITOR.dialog.getCurrent().getContentElement("info",a).focus();0<c.indexOf("Link")&&CKEDITOR.dialog.getCurrent().setValueOf("info",
"protocol","")}}}
function convertRGBToHex(d){return 0>d.indexOf("rgba")?d.replace(/(?:rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\))/gi,function(a,c,b,d){c=parseInt(c,10).toString(16);b=parseInt(b,10).toString(16);d=parseInt(d,10).toString(16);a=[c,b,d];for(c=0;c<a.length;c++)a[c]=String("0"+a[c]).slice(-2);return"#"+a.join("")}):d.replace(/(?:rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\))/gi,function(a,c,b,d,f){c=parseInt(c,10).toString(16);b=parseInt(b,10).toString(16);d=parseInt(d,10).toString(16);a=[c,
b,d];for(var e=0;e<a.length;e++)a[e]=String("0"+a[e]).slice(-2);return 0==f&&0==c&&0==b&&0==d?"transparent":"#"+a.join("")})};