	/************************************************************************************************************
  #############################################################################
  #                SuperMailingList / SuperWebMailer                          #
  #               Copyright © 2007 - 2015 Mirko Boeer                         #
  #                    Alle Rechte vorbehalten.                               #
  #                http://www.supermailinglist.de/                            #
  #                http://www.superwebmailer.de/                              #
  #   Support SuperMailingList: support@supermailinglist.de                   #
  #   Support SuperWebMailer: support@superwebmailer.de                       #
  #   Support-Forum: http://board.superscripte.de/                            #
  #                                                                           #
  #   Dieses Script ist urheberrechtlich geschuetzt. Zur Nutzung des Scripts  #
  #   muss eine Lizenz erworben werden.                                       #
  #                                                                           #
  #   Das Script darf weder als ganzes oder als Teil eines anderen Projekts   #
  #   verwendet oder weiterverkauft werden.                                   #
  #                                                                           #
  #   Beachten Sie fuer den Einsatz des Script-Pakets die Lizenzbedingungen   #
  #                                                                           #
  #   Fuehren Sie keine Veraenderungen an diesem Script durch. Jegliche       #
  #   Veraenderungen koennen nicht supported werden.                          #
  #                                                                           #
  #############################################################################
	************************************************************************************************************/

var createtableofcontents=!1,item_id=1,repeater_item_id=1,Initialized=!1;
function MakeRepeatersSortable(){$(".ipe_repeater").sortable("destroy");$(".ipe_repeater").sortable({opacity:.9,scroll:!0,handle:$(".ipe_move"),items:".ipe_repeater_item",connectWith:$(".ipe_repeater"),placeholder:"ipe_hover",forceHelperSize:!0,forcePlaceholderSize:!0,cursor:"crosschair",tolerance:"pointer",activate:function(a,b){},over:function(a,b){},start:function(a,b){$(".ipe_repeater").addClass("show_repeaterborder")},stop:function(a,b){$(".ipe_repeater").removeClass("show_repeaterborder");$(".ipe_repeater_item").removeClass("ipe_repeater_item_hover");
$(".ipe_move").removeClass("ui-state-hover");$(".ipe_repeater_item").css("left",null);$(".ipe_repeater_item").css("top",null);$(".ipe_repeater_item").css("right",null);$(".ipe_repeater_item").css("height",null);$(".ipe_repeater_item").css("position",null);$(".ipe_repeater_item").css("opacity",null);SortTableOfContents();parent.Modified=!0;$(".ipe_repeater").each(function(){$(this).append($(this).find(".ipe_repeater_toolbar:first"))})}});$(".ipe_repeater_toolbar").disableSelection()}
function SetupIPEItem(a){$(a).find(".ipe_toolbar").html()||($(a).prepend('<div class="ipe_toolbar"></div>'),$(a).find(".ipe_toolbar:first").append('<div class="ipe_edit ui-button ui-icon ui-icon-pencil ui-state-default ui-corner-all" title="'+rsEditItem+'"></div>'),parent.document.getElementById("TargetGroupsSupport")&&1==parent.document.getElementById("TargetGroupsSupport").value&&parent.document.getElementById("TargetGroupsDefined")&&1==parent.document.getElementById("TargetGroupsDefined").value&&
$(a).find(".ipe_toolbar:first").append('<div class="ipe_targetgroups ui-button ui-icon ui-icon-person ui-state-default ui-corner-all" title="'+rsTargetGroups+'"></div>'));$(a).attr("id",item_id++);$(a).attr("title",rsDoubleClickToEdit);$(a).off("click");$(a).click(function(a){a.stopPropagation();EditItem($(this));return!1});$(a).find(".ipe_toolbar").find(".ipe_edit").off("click");$(a).find(".ipe_toolbar").find(".ipe_edit").click(function(a){a.stopPropagation();EditItem($(this).closest(".ipe_item"))});
$(a).find(".ipe_toolbar").find(".ipe_targetgroups").off("click");$(a).find(".ipe_toolbar").find(".ipe_targetgroups").click(function(a){a.stopPropagation();ShowTargetGroupsDialog($(this).closest(".ipe_item"))});$(a).find(".ipe_toolbar").find(".ipe_edit,.ipe_targetgroups").off("hover");$(a).find(".ipe_toolbar").find(".ipe_edit,.ipe_targetgroups").hover(function(a){$(this).addClass("ui-state-hover");$(this).closest(".ipe_item").addClass("ipe_hover")},function(){$(this).removeClass("ui-state-hover");
createtableofcontents&&($(this).closest(".ipe_item").parent().addClass("ipe_hover"),$(this).closest(".ipe_item").parent().removeClass("ipe_hover"));$(this).closest(".ipe_item").removeClass("ipe_hover")});$(a).find(".ipe_toolbar").off("click");$(a).find(".ipe_toolbar").click(function(a){a.stopPropagation()})}
function SetupRepeaterItem(a){$(a).find(".ipe_toolbar").html()||$(a).prepend("<div class='ipe_toolbar'></div>");$(a).attr("editable")&&!$(a).find(".ipe_toolbar").find(".ipe_cssedit").attr("class")&&$(a).find(".ipe_toolbar:first").append("<div class='ipe_cssedit ui-button ui-icon ui-icon-wrench ui-state-default ui-corner-all' title='"+rsCSSEditItem+"'></div>");$(a).find(".ipe_toolbar").find(".ipe_move").attr("class")||($(a).find(".ipe_toolbar:first").append("<div class='ipe_move ui-button ui-icon ui-icon-arrow-4-diag ui-state-default ui-corner-all' title='"+
rsMoveItem+"'></div>"),$(a).find(".ipe_toolbar:first").append("<div class='ipe_delete ui-button ui-icon ui-icon-trash ui-state-default ui-corner-all' title='"+rsDeleteItem+"'></div>"));$(a).find(".ipe_toolbar").off("click");$(a).find(".ipe_toolbar").click(function(a){a.stopPropagation()});$(a).find(".ipe_toolbar").find(".ipe_move").off("hover");$(a).find(".ipe_toolbar").find(".ipe_move").hover(function(a){$(this).addClass("ui-state-hover");$(this).css("cursor","move");$(this).closest(".ipe_repeater_item").addClass("ipe_repeater_item_hover")},
function(a){$(this).closest(".ipe_repeater_item").removeClass("ipe_repeater_item_hover");$(this).css("cursor","auto");$(this).removeClass("ui-state-hover")});$(a).find(".ipe_toolbar").find(".ipe_delete").off("hover");$(a).find(".ipe_toolbar").find(".ipe_delete").hover(function(a){$(this).addClass("ui-state-hover");$(this).closest(".ipe_repeater_item").addClass("ipe_repeater_item_hover")},function(a){$(this).closest(".ipe_repeater_item").removeClass("ipe_repeater_item_hover");$(this).removeClass("ui-state-hover")});
$(a).find(".ipe_toolbar").find(".ipe_cssedit").off("hover");$(a).find(".ipe_toolbar").find(".ipe_cssedit").hover(function(a){$(this).addClass("ui-state-hover");$(this).closest(".ipe_repeater_item").addClass("ipe_repeater_item_hover")},function(a){$(this).closest(".ipe_repeater_item").removeClass("ipe_repeater_item_hover");$(this).removeClass("ui-state-hover")});$(a).find(".ipe_cssedit").off("click");$(a).find(".ipe_cssedit").click(function(a){a.stopPropagation();a=$(this).closest(".editable");CSSEditor(a)});
$(a).find(".ipe_delete").off("click");$(a).find(".ipe_delete").click(function(a){a.stopPropagation();var c=$(this).closest(".ipe_item").attr("id"),d=$(this);parent.$("#dialog-removeitem").dialog("destroy");parent.$("#dialog-removeitem").dialog({resizable:!1,draggable:!1,height:150,modal:!0});parent.$("#dialog-removeitem").dialog("option","buttons",[{text:rsYes,click:function(){parent.$(this).dialog("close");RemoveTableOfContentsEntry(c);tableofcontentsincludedoncemore=!1;"true"==d.closest(".ipe_repeater_item").attr("tableofcontents_mainitem")&&
(tableofcontentsincludedoncemore=RemoveTableOfContents(d.closest(".ipe_repeater_item")));d.closest(".ipe_repeater_item").removeClass("ipe_repeater_item_hover");d.closest(".ipe_repeater_item").remove();parent.Modified=!0;tableofcontentsincludedoncemore&&CreateTableOfContents()}},{text:rsNo,click:function(){parent.$(this).dialog("close");d.closest(".ipe_repeater_item").removeClass("ipe_repeater_item_hover")}}])});MakeRepeatersSortable()}
function Init_IPE(){var a=!1;InitializeTemplate();item_id=1;$(".ipe_item").each(function(){SetupIPEItem(this);a=!0});$(".ipe_repeater").each(function(){if(!$(this).find(".ipe_repeater_toolbar").html()){$(this).append("<div class='ipe_repeater_toolbar'></div>");var b=$(this).attr("label")?$(this).attr("label"):rsAdd;$(this).find(".ipe_repeater_toolbar").append("<div class='ipe_addrepeater_item ui-button ui-state-default ui-corner-all' style='font-size:0.8em;font-weight:normal;'>"+b+"</div>");$(this).find(".ipe_repeater_toolbar").find(".ipe_addrepeater_item").button({text:!0,
icons:{primary:"ui-icon-plus",secondary:""}});$(this).find(".ipe_repeater_toolbar").append("<div class='ipe_newrepeater_item ui-button ui-state-default ui-corner-all' style='font-size:0.8em;font-weight:normal;'>"+rsNew+"</div>");$(this).find(".ipe_repeater_toolbar").find(".ipe_newrepeater_item").button({text:!0,icons:{primary:"ui-icon-arrowreturnthick-1-e",secondary:""}});a=!0}});$(".ipe_repeater_toolbar").find(".ipe_addrepeater_item").off("click");$(".ipe_repeater_toolbar").find(".ipe_addrepeater_item").click(function(){$(this).removeClass("ui-state-hover");
var a=$(this).closest(".ipe_repeater").attr("repeateritemdata")?utf8_decode(decodeURIComponent($(this).closest(".ipe_repeater").attr("repeateritemdata").replace(/\+/g," "))):"<div>No template found.</div>",c=$(this).closest(".ipe_repeater").attr("label")?$(this).closest(".ipe_repeater").attr("label"):"";AddRepeaterItem($(this).closest(".ipe_repeater"),a,c)});$(".ipe_repeater_toolbar").find(".ipe_newrepeater_item").off("click");$(".ipe_repeater_toolbar").find(".ipe_newrepeater_item").click(function(){$(this).removeClass("ui-state-hover");
NewRepeaterItem($(this))});$(".ipe_repeater_item").each(function(){SetupRepeaterItem(this);a=!0});a||parent.MessageBox(rsWarning,rsTemplateUnsuitable,parent.messageTypeWarning,380,130,"",!1)}
parent.inherit(window)(function(){$(document).ready(function(){rsAdd=parent.rsAdd;rsNew=parent.rsNew;rsMoveItem=parent.rsMoveItem;rsEditItem=parent.rsEditItem;rsCSSEditItem=parent.rsCSSEditItem;rsDeleteItem=parent.rsDeleteItem;rsDoubleClickToEdit=parent.rsDoubleClickToEdit;rsApply=parent.rsApply;rsCancel=parent.rsCancel;rsYes=parent.rsYes;rsNo=parent.rsNo;rsWarning=parent.rsWarning;rsTemplateUnsuitable=parent.rsTemplateUnsuitable;rsTargetGroups=parent.rsTargetGroups;_IPE()})});
function _IPE(){Initialized||(Init_IPE(),parent.Modified=!1,CreateTableOfContents(),Initialized=!0)}
function InitializeTemplate(){for(var a=["singleline","multiline"],b=0;b<a.length;b++)$(a[b]).each(function(c){c="";$(this).attr("label")&&(c=$(this).attr("label"));var d="";$(this).attr("target_groups")&&(d=' target_groups="'+$(this).attr("target_groups")+'"');if("singleline"==a[b]){var e="false";"true"==$(this).attr("tableofcontentstitle")&&(e=$(this).attr("tableofcontentstitle"));$(this).wrap('<div class="ipe_item" rel="'+a[b]+'"  style="" label="'+c+'" tableofcontentstitle="'+e+'"'+d+"></div>")}else $(this).wrap('<div class="ipe_item" rel="'+
a[b]+'"  style="" label="'+c+'"'+d+"></div>");$(this).children().html()?$(this).children().unwrap():($(this).html(),$(this).parent().html($(this).html()),$(this).remove())});$('div[class="socialmedia"]').each(function(a){a="";$(this).attr("label")&&(a=$(this).attr("label"));var b="";$(this).attr("target_groups")&&(b=' target_groups="'+$(this).attr("target_groups")+'"');$(this).wrap('<div class="ipe_item" rel="socialmedia"  style="" label="'+a+'"'+b+"></div>");$(this).attr("class",null)});$("img").each(function(a){if($(this).attr("editable")&&
"true"==$(this).attr("editable")){if("multiline"!=$(this).closest(".ipe_item").attr("rel")){a="";$(this).attr("label")&&(a=$(this).attr("label"));var b="";$(this).attr("target_groups")&&(b=' target_groups="'+$(this).attr("target_groups")+'"');$(this).wrap('<div class="ipe_item" rel="img"  style="" label="'+a+'"'+b+"></div>")}$(this).attr("editable",null)}});$("hr").each(function(a){if($(this).attr("editable")&&"true"==$(this).attr("editable")){if("multiline"!=$(this).closest(".ipe_item").attr("rel")){a=
"";$(this).attr("label")&&(a=$(this).attr("label"));var b="";$(this).attr("target_groups")&&(b=' target_groups="'+$(this).attr("target_groups")+'"');$(this).wrap('<div class="ipe_item" rel="hr"  style="" label="'+a+'"'+b+"></div>")}$(this).attr("editable",null)}});$("ul, ol").each(function(a){if($(this).attr("editable")&&"true"==$(this).attr("editable")){if("multiline"!=$(this).closest(".ipe_item").attr("rel")){a="";$(this).attr("label")&&(a=$(this).attr("label"));var b="";$(this).attr("target_groups")&&
(b=' target_groups="'+$(this).attr("target_groups")+'"');$(this).wrap('<div class="ipe_item" rel="'+$(this).get(0).tagName.toLowerCase()+'"  style="" label="'+a+'"'+b+"></div>")}$(this).attr("editable",null)}});$("a").each(function(a){if("true"==$(this).attr("editable")&&(""==$(this).attr("name")||null==$(this).attr("name"))){if("multiline"!=$(this).closest(".ipe_item").attr("rel")){a="";$(this).attr("label")&&(a=$(this).attr("label"));var b="";$(this).attr("target_groups")&&(b=' target_groups="'+
$(this).attr("target_groups")+'"');$(this).wrap('<div class="ipe_item" rel="a"  style="display:inline" label="'+a+'"'+b+"></div>")}$(this).attr("editable",null)}});$("repeater").each(function(a){a=$(this).attr("repeateritemdata")?$(this).attr("repeateritemdata"):encodeURIComponent(utf8_encode($(this).html()));var b="",e=!1;$(this).attr("label")&&(b=$(this).attr("label"));var g="";$(this).attr("target_groups")&&(g=' target_groups="'+$(this).attr("target_groups")+'"');$(this).attr("editable")&&"true"==
$(this).attr("editable")&&(e=!0);var f="";e&&(f='editable="true"');$(this).wrap('<div class="ipe_repeater" rel="repeater" id="'+repeater_item_id+'" style="" label="'+b+'" repeateritemdata="'+a+'" '+f+g+"></div>");$(this).wrap('<div class="ipe_repeater_item" rel="repeater_item" id="'+repeater_item_id+'-0" style="" label="'+b+'" '+f+g+"></div>");e&&$(this).wrap('<div class="editable" style=""'+f+g+"></div>");repeater_item_id++;$(this).children().unwrap()});(createtableofcontents=""!=$("tableofcontents").html()||
$('div[id="tableofcontents"]').html())&&$("tableofcontents").each(function(){if($(this).html()){var a="";$(this).attr("style")&&(a=' style="'+$(this).attr("style")+'"');var b="";$(this).attr("class")&&(b=' class="'+$(this).attr("class")+'"');var e=encodeURIComponent(utf8_encode($(this).html()));$(this).wrap('<div id="tableofcontents" tableofcontentsdata="'+e+'"'+a+b+"></div>");$(this).children().unwrap()}})}
function AddRepeaterItem(a,b,c){$("#no_template_loaded").remove();var d=!1;$(a).attr("editable")&&(d=!0);0<=b.indexOf('editable="false"')&&(d=!1);$(a).find(".ipe_repeater_toolbar").before('<div class="ipe_repeater_itemNEW" id="ipe_repeater_itemNEW"></div>');var e=$(a).find(".ipe_repeater_itemNEW");e.attr("class","ipe_repeater_item");e.attr("rel","repeater_item");e.attr("label",c);d&&(e.attr("editable","true"),b='<div class="editable" style="" editable="true">'+b+"</div>");(-1<b.indexOf("<tableofcontents>")||
-1<b.indexOf("<TABLEOFCONTENTS>"))&&e.attr("tableofcontents_mainitem","true");e.html(b);$(a).find(".ipe_repeater_item").each(function(b){$(this).attr("id",a.attr("id")+"-"+b)});Init_IPE();CreateTableOfContents();parent.Modified=!0}
function NewRepeaterItem(a){$("#no_template_loaded").remove();parent.$("#dialog-new").dialog("destroy");parent.$("#dialog-new").dialog({resizable:!0,modal:!0,width:650,height:500,close:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover")}});parent.LoadNewIPEElements("dialog-new_items");parent.$("#dialog-new").dialog("option","buttons",[{text:html_entity_decode(rsApply),click:function(){parent.$(this).dialog("close");
var b=parent.$(this).find(".ui-selected").children().attr("rel");if(null!=b){var c=(new Date).getTime()/1E3;jQuery.get("ajax_load_new_ipe_elements.php?nocache="+c+"&filename="+b,"",function(b){AddRepeaterItem(a.closest(".ipe_repeater"),b,$(this).closest(".ipe_repeater").attr("label")?$(this).closest(".ipe_repeater").attr("label"):"")});parent.Modified=!0}}},{text:rsCancel,click:function(){parent.$(this).dialog("close")}}])}
function CreateTableOfContents(){createtableofcontents&&$('div[id="tableofcontents"]').each(function(){var a=$(this),b=utf8_decode(decodeURIComponent($(a).attr("tableofcontentsdata")));$(this).find("a").each(function(){var a=$(this).attr("href").substr(1);$(this).remove();$("body").find('a[id*="'+a+'"]').each(function(){$(this).remove()})});$(a).html("");$(".ipe_item").each(function(c){if(!$(this).attr("tableofcontentstitle")||"false"==$(this).attr("tableofcontentstitle")||"singleline"!=$(this).attr("rel"))return!0;
var e=$(this).clone(!1);e.find(".ipe_toolbar").remove();c=RemoveDoubleSpacesInSingleLine(e.text().trim());e.remove();$(a).append(b);var g=e="";$(a).find("tableofcontentstitle").attr("style")?e=' style="'+$(a).find("tableofcontentstitle").attr("style")+'"':$(a).attr("style")&&(e=' style="'+$(a).attr("style")+'"');$(a).find("tableofcontentstitle").attr("class")?g=' class="'+$(a).find("tableofcontentstitle").attr("class")+'"':$(a).attr("class")&&(g=' class="'+$(a).attr("class")+'"');$(a).find("tableofcontentstitle").parent().append('<a href="#anchor_'+
$(this).attr("id")+'"'+e+g+">"+c+"</a>");$(a).find("tableofcontentstitle").remove();c='a[id="anchor_'+$(this).attr("id")+'"]';null==$("body").find(c).attr("id")&&$(this).before('<a rel="tableofcontentsentry" name="anchor_'+$(this).attr("id")+'" id="anchor_'+$(this).attr("id")+'"></a>')});if($.browser.msie&&9>parseInt($.browser.version,10)){var c=$(a).html(),c=c.replace(/\<\/TABLEOFCONTENTSTITLE\>/ig,"");$(a).html(c)}})}
function RemoveTableOfContents(a){if(!createtableofcontents)return!1;var b=!1;$('div[id="tableofcontents"]').each(function(){null!=a&&a.attr("id")!=$(this).closest(".ipe_repeater_item").attr("id")&&(b=!0);var c=$(this);$(c).empty()});$("body").find('a[rel="tableofcontentsentry"]').each(function(){$(this).remove()});b||(createtableofcontents=!1);return b}
function RemoveTableOfContentsEntry(a){createtableofcontents&&(a="anchor_"+a,$("body").find('a[href*="#'+a+'"]').each(function(){$(this).parent().children().unwrap();$(this).remove()}),$("body").find('a[id*="'+a+'"]').each(function(){$(this).remove()}))}function EditTableOfContentsEntry(a,b){if(createtableofcontents){var c="anchor_"+a;$("body").find('a[href*="#'+c+'"]').each(function(){$(this).text(b)})}}function SortTableOfContents(){CreateTableOfContents()}
function EditItem(a){$("#no_template_loaded").remove();if("singleline"==$(a).attr("rel")){$(a).attr("label")?parent.$("#labelForSingleline").html($(a).attr("label")):parent.$("#labelForSingleline").html(parent.$("#labelForSingleline").attr("defaulttitle"));parent.$("#dialog-singleline").dialog("destroy");parent.$("#dialog-singleline").dialog({resizable:!1,modal:!0,width:600,close:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");
MakeRepeatersSortable()}});parent.$("#dialog-singleline").find("input").keypress(function(a){if(a.which&&13==a.which||a.keyCode&&13==a.keyCode)return $(this).parent().parent().parent().parent().find(".ui-dialog-buttonpane").find("button:first").click(),!1});var b=parent.$("#singleline"),c=parent.$("#singleline_hyperlink"),d=$(a).find(".ipe_toolbar").clone(!0);$(a).find(".ipe_toolbar").remove();null==$(a).find("a").attr("href")?(b.val(RemoveDoubleSpacesInSingleLine($(a).text().trim())),c.val("")):
(b.val(RemoveDoubleSpacesInSingleLine($(a).text().trim())),c.val($(a).find("a").attr("href")));$(a).prepend(d);parent.$("#dialog-singleline").dialog("option","buttons",[{text:html_entity_decode(rsApply),click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");parent.$(this).dialog("close");var p=$(a).find(".ipe_toolbar").clone(!0);$(a).find(".ipe_toolbar").remove();$(a).empty();if(""==c.val().trim())$(a).text(b.val().trim());
else{var d=c.val().trim();0>d.indexOf("http")&&0>d.indexOf("mailto:")&&0!=d.indexOf("[")&&(d="http://"+d);$(a).html('<a href="'+d+'">'+b.val().trim()+"</a>")}$(a).prepend(p);parent.Modified=!0;EditTableOfContentsEntry($(a).attr("id"),b.val().trim());MakeRepeatersSortable()}},{text:rsCancel,click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");parent.$(this).dialog("close")}}])}if("img"==$(a).attr("rel")){$(a).attr("label")?
parent.$("#labelForImage").html($(a).attr("label")):parent.$("#labelForImage").html(parent.$("#labelForImage").attr("defaulttitle"));parent.$("#dialog-image").dialog("destroy");parent.$("#dialog-image").dialog({resizable:!1,modal:!0,width:600,close:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover")}});parent.$("#dialog-image").find("input").keypress(function(a){if(a.which&&13==a.which||a.keyCode&&13==a.keyCode)return $(this).parent().parent().parent().parent().find(".ui-dialog-buttonpane").find("button:first").click(),
!1});var e=parent.$("#imageurl"),g=parent.$("#alttext"),f=parent.$("#image_hyperlinkurl");e.val($(a).find("img").attr("src"));g.val($(a).find("img").attr("alt"));d=$(a).find("img").attr("src");-1==d.indexOf("http:")&&-1==d.indexOf("https:")?parent.$("#chkassiInsertImageAsCompleteURL").attr("checked",!1):parent.$("#chkassiInsertImageAsCompleteURL").attr("checked",!0);null==$(a).find("a").attr("href")?f.val(""):f.val($(a).find("a").attr("href"));parent.$("#dialog-image").dialog("option","buttons",[{text:html_entity_decode(rsApply),
click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");$(a).find("img").attr("src",e.val().trim());$(a).find("img").attr("alt",g.val().trim());if(""==f.val().trim())$(a).find("a").children().unwrap();else{$(a).find("a").children().unwrap();var b=f.val().trim();0>b.indexOf("http")&&0>b.indexOf("mailto:")&&0!=b.indexOf("[")&&(b="http://"+b);$(a).find("img").wrap('<a href="'+b+'"></a>')}parent.$(this).dialog("close");
parent.Modified=!0}},{text:rsCancel,click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");parent.$(this).dialog("close")}}])}if("a"==$(a).attr("rel")){$(a).attr("label")?parent.$("#labelForHyperlink").html($(a).attr("label")):parent.$("#labelForHyperlink").html(parent.$("#labelForHyperlink").attr("defaulttitle"));parent.$("#dialog-hyperlink").dialog("destroy");parent.$("#dialog-hyperlink").dialog({resizable:!1,
modal:!0,width:600,close:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover")}});parent.$("#dialog-hyperlink").find("input").keypress(function(a){if(a.which&&13==a.which||a.keyCode&&13==a.keyCode)return $(this).parent().parent().parent().parent().find(".ui-dialog-buttonpane").find("button:first").click(),!1});var n=parent.$("#hyperlink"),k=parent.$("#textforhyperlink");n.val($(a).find("a").attr("href"));k.val(RemoveDoubleSpacesInSingleLine($(a).find("a").text().trim()));
parent.$("#dialog-hyperlink").dialog("option","buttons",[{text:html_entity_decode(rsApply),click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");parent.$(this).dialog("close");var b=n.val().trim();0>b.indexOf("http")&&0>b.indexOf("mailto:")&&0!=b.indexOf("#")&&0!=b.indexOf("[")&&(b="http://"+b);$(a).find("a").attr("href",b);""!=k.val().trim()?$(a).find("a").text(k.val().trim()):$(a).find("a").text(b);parent.Modified=
!0}},{text:rsCancel,click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");parent.$(this).dialog("close")}}])}if("multiline"==$(a).attr("rel")){$(a).attr("label")?parent.$("#labelForMultiline").html($(a).attr("label")):parent.$("#labelForMultiline").html(parent.$("#labelForMultiline").attr("defaulttitle"));var l=parent.$("#multiline"),d=$(a).find(".ipe_toolbar").clone(!0);$(a).find(".ipe_toolbar").remove();var q=
$(a).html().replace(/\n/g," ").replace(/ +/g," ").replace(/\t/g,"");$(a).prepend(d);parent.$("#dialog-multiline").dialog({resizable:!1,autoOpen:!0,modal:!0,width:700,open:function(){l.val(q);parent.LoadMultilineToCKEditor()},close:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");MakeRepeatersSortable()}});parent.$("#dialog-multiline").find("input").keypress(function(a){if(a.which&&13==a.which||a.keyCode&&13==a.keyCode)return $(this).parent().parent().parent().parent().find(".ui-dialog-buttonpane").find("button:first").click(),
!1});parent.$("#dialog-multiline").dialog("option","position","center");parent.$("#dialog-multiline").dialog("option","buttons",[{text:html_entity_decode(rsApply),click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");try{parent.CKEDITOR.instances.multiline.updateElement()}catch(b){alert("Error getting content of editor")}parent.$(this).dialog("close");var c=$(a).find(".ipe_toolbar").clone(!0);$(a).find(".ipe_toolbar").remove();
$(a).empty();$(a).html(l.val());$(a).prepend(c);parent.Modified=!0;l.val("")}},{text:rsCancel,click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");parent.$(this).dialog("close")}}])}"hr"==$(a).attr("rel")&&(parent.$("#dialog-hr").dialog("destroy"),parent.$("#dialog-hr").dialog({resizable:!1,modal:!0,width:600,closeOnEscape:!1,close:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");
parent.CloseColorPicker()}}),parent.$("#dialog-hr").find("input").keypress(function(a){if(a.which&&13==a.which||a.keyCode&&13==a.keyCode)return $(this).parent().parent().parent().parent().find(".ui-dialog-buttonpane").find("button:first").click(),!1}),null!=$(a).find("hr").attr("width")?parent.$("#hr_width").val($(a).find("hr").attr("width")):parent.$("#hr_width").val($(a).find("hr").css("width")),null!=$(a).find("hr").attr("size")?parent.$("#hr_height").val($(a).find("hr").attr("size")+"px"):parent.$("#hr_height").val($(a).find("hr").css("height")),
null!=$(a).find("hr").css("text-align")?parent.$("#hralignmentCB").val($(a).find("hr").css("text-align")):parent.$("#hralignmentCB").val("left"),null!=$(a).find("hr").attr("color")?parent.$("#hr_color").val($(a).find("hr").attr("color")):null!=$(a).find("hr").css("color")&&parent.$("#hr_color").val(convertRGBToHex($(a).find("hr").css("color"))),null!=$(a).find("hr").attr("noshade")?parent.$("#hr_noshade").attr("checked","on"):parent.$("#hr_noshade").attr("checked",null),parent.$("#dialog-hr").dialog("option",
"buttons",[{text:html_entity_decode(rsApply),click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");$(a).find("hr").attr("width",null);$(a).find("hr").attr("size",null);$(a).find("hr").attr("align",null);$(a).find("hr").attr("color",null);$(a).find("hr").attr("width",parent.$("#hr_width").val());$(a).find("hr").css("width",parent.$("#hr_width").val());$(a).find("hr").css("height",parent.$("#hr_height").val());$(a).find("hr").css("text-align",
parent.$("#hralignmentCB").val());$(a).find("hr").attr("color",parent.$("#hr_color").val());$(a).find("hr").css("color",parent.$("#hr_color").val());$(a).find("hr").css("background-color",parent.$("#hr_color").val());null!=parent.$("#hr_noshade").attr("checked")?$(a).find("hr").attr("noshade","noshade"):$(a).find("hr").attr("noshade",null);parent.$(this).dialog("close");parent.Modified=!0}},{text:rsCancel,click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");
parent.$(this).dialog("close")}}]));if("ul"==$(a).attr("rel")||"ol"==$(a).attr("rel"))parent.$("#dialog-list").dialog("destroy"),parent.$("#dialog-list").dialog({resizable:!1,modal:!0,width:600,closeOnEscape:!1,close:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover")},open:function(){parent.$("#dialog-list-edit").attr("disabled","disabled");parent.$("#dialog-list-edit").addClass("ui-state-disabled");parent.$("#dialog-list-remove").attr("disabled",
"disabled");parent.$("#dialog-list-remove").addClass("ui-state-disabled");parent.MakeListEntriesSelectable();parent.ActivateDeactivateUpDownBtns()}}),parent.$("#dialog-list").find("input").keypress(function(a){if(a.which&&13==a.which||a.keyCode&&13==a.keyCode)return $(this).parent().parent().parent().parent().find(".ui-dialog-buttonpane").find("button:first").click(),!1}),parent.$("#dialog-list").find("#dialog-list-elements").html(""),d=$(a).clone(!1),$(d).find(".ipe_toolbar").remove(),$(d).find("li").each(function(){$(this).attr("class",
"ui-state-default");$(this).append('<div class="li_delete ui-button ui-icon ui-icon-trash ui-corner-all" title="'+rsDeleteItem+'"></div>')}),null!=$(a).find("ul, ol").css("list-style-type")?parent.$("#ListStyleTypeCB").val($(a).find("ul, ol").css("list-style-type")):parent.$("#ListStyleTypeCB").val("disc"),null!=$(a).find("ul, ol").css("text-align")?parent.$("#ListalignmentCB").val($(a).find("ul, ol").css("text-align")):parent.$("#ListalignmentCB").val("left"),d.find("ul, ol").children()?d.find("ul, ol").children().unwrap():
d.html(""),parent.$("#dialog-list-elements").prepend(d.html()),d=null,parent.MakeListEntriesSelectable(),parent.$("#dialog-list").dialog("option","buttons",[{text:html_entity_decode(rsApply),click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");parent.$(this).dialog("close");$(a).find("ul, ol").css("list-style-type",parent.$("#ListStyleTypeCB").val());$(a).find("ul, ol").css("text-align",parent.$("#ListalignmentCB").val());
$(a).find("ul, ol").html("");var b=parent.$(this).find("ul, ol");b.find(".li_delete").remove();b.find("li").attr("class",null);$(a).find("ul, ol").prepend(b.html());parent.Modified=!0}},{text:rsCancel,click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");parent.$(this).dialog("close")}}]);if("socialmedia"==$(a).attr("rel")){$(a).attr("label")?parent.$("#labelForSocialMedia").html($(a).attr("label")):parent.$("#labelForSocialMedia").html(parent.$("#labelForSocialMedia").attr("defaulttitle"));
parent.$("#dialog-socialmedia").dialog("destroy");parent.$("#dialog-socialmedia").dialog({resizable:!1,modal:!0,width:600,close:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");MakeRepeatersSortable()}});parent.$("#dialog-socialmedia").find("input").keypress(function(a){if(a.which&&13==a.which||a.keyCode&&13==a.keyCode)return $(this).parent().parent().parent().parent().find(".ui-dialog-buttonpane").find("button:first").click(),
!1});var h=parent.$("#socialmediabar"),m=parent.$("#smbaralignmentCB"),d=(new Date).getTime()/1E3;jQuery.get("ajax_load_new_ipe_elements.php?nocache="+d+"&filename=socialmediashare.htm&smechkboxes=true","",function(b){h.html(b);$(a).find(".socialmedia_item").each(function(){h.find("#"+$(this).attr("id")).find("input").attr("checked",!0)});null!=$(a).css("text-align")?m.val($(a).css("text-align")):m.val("left");h.find(".socialmedia_item").hover(function(a){$(this).addClass("ui-state-hover")},function(){$(this).removeClass("ui-state-hover")});
h.find(".socialmedia_item").off("click");h.find(".socialmedia_item").click(function(a){a.stopPropagation();$(this).find("input").attr("checked",!$(this).find("input").attr("checked"))});h.find(".socialmedia_item").find("input").off("click");h.find(".socialmedia_item").find("input").click(function(a){a.stopPropagation()});h.find(".socialmedia_item").find("a").off("click");h.find(".socialmedia_item").find("a").click(function(a){a.stopPropagation();$(this).parent().find("input").attr("checked",!$(this).parent().find("input").attr("checked"));
return!1})});parent.$("#dialog-socialmedia").dialog("option","buttons",[{text:html_entity_decode(rsApply),click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");$(a).css("text-align",m.val());$(a).find("#socialmedia").html("");h.find(".socialmedia_item").each(function(){if($(this).find("input").attr("checked")){$(this).find("input").remove();$(this).find("br").remove();var b=$(this).clone();$(a).find("#socialmedia").append(b)}});
parent.$(this).dialog("close");parent.Modified=!0}},{text:rsCancel,click:function(){$(a).closest(".ipe_item").removeClass("ipe_hover");$(a).find(".ipe_toolbar").find(".ipe_edit").removeClass("ui-state-hover");parent.$(this).dialog("close")}}])}}
function ShowTargetGroupsDialog(a){var b=a.attr("target_groups");parent.$("#dialog-targetgroups").dialog({resizable:!1,modal:!0,width:600,open:function(){try{parent.document.getElementById("__wizardtargetgroupsIframe").contentWindow.UnCheckAll()}catch(a){}parent.$("#dialog-targetgroups").find("#_edit_target_groups").val(b);parent.document.getElementById("__wizardtargetgroupsIframe").src="./ajax_showtargetgroups.php?wizard=wizard"}});parent.$("#dialog-targetgroups").find("input").keypress(function(a){if(a.which&&
13==a.which||a.keyCode&&13==a.keyCode)return $(this).parent().parent().parent().parent().find(".ui-dialog-buttonpane").find("button:first").click(),!1});parent.$("#dialog-targetgroups").dialog("option","buttons",[{text:html_entity_decode(rsApply),click:function(){(b=parent.document.getElementById("__wizardtargetgroupsIframe").contentWindow.GetCheckedTargetGroups())?a.attr("target_groups",b):a.attr("target_groups",null);parent.$(this).dialog("close");return parent.Modified=!0}},{text:rsCancel,click:function(){parent.$(this).dialog("close")}}]);
return!1}
function CSSEditor(a){$("#no_template_loaded").remove();parent.$("#dialog-cssedit").dialog("destroy");parent.$("#dialog-cssedit").dialog({resizable:!1,modal:!0,width:600,closeOnEscape:!1,close:function(){$(a).removeClass("ipe_repeater_item_hover");$(a).find(".ipe_toolbar").find(".ipe_cssedit").removeClass("ui-state-hover");parent.CloseColorPicker()}});parent.$("#dialog-cssedit").find("#fontName").val($(a).css("font-family"));parent.$("#dialog-cssedit").find("#fontSize").val($(a).css("font-size"));parent.$("#dialog-cssedit").find("#fontcolor").val(convertRGBToHex($(a).css("color")));
parent.$("#dialog-cssedit").find("#bgcolor").val(convertRGBToHex($(a).css("background-color")));parent.$("#dialog-cssedit").find("#width").val($(a).css("width"));parent.$("#dialog-cssedit").find("#height").val($(a).css("height"));var b=["","-top","-left","-right","-bottom"];parent.$("#dialog-cssedit").find("#padding").val("");for(var c=0;c<b.length;c++)if(null!=$(a).css("padding"+b[c])&&"none"!=$(a).css("padding"+b[c])&&""!=$(a).css("padding"+b[c])){parent.$("#dialog-cssedit").find("#padding").val($(a).css("padding"+
b[c]));break}parent.$("#dialog-cssedit").find("#margin").val("");for(c=0;c<b.length;c++)if(null!=$(a).css("margin"+b[c])&&"none"!=$(a).css("margin"+b[c])&&""!=$(a).css("margin"+b[c])){parent.$("#dialog-cssedit").find("#margin").val($(a).css("margin"+b[c]));break}b=["","-top-","-left-","-right-","-bottom-"];parent.$("#dialog-cssedit").find("#borderStyle").val("none");for(c=0;c<b.length;c++)if(null!=$(a).css("border"+b[c]+"style")&&"none"!=$(a).css("border"+b[c]+"style")&&""!=$(a).css("border"+b[c]+
"style")){parent.$("#dialog-cssedit").find("#borderStyle").val($(a).css("border"+b[c]+"style"));break}parent.$("#dialog-cssedit").find("#borderWidth").val("");for(c=0;c<b.length;c++)null!=$(a).css("border"+b[c]+"width")&&"none"!=$(a).css("border"+b[c]+"width")&&""!=$(a).css("border"+b[c]+"width")&&parent.$("#dialog-cssedit").find("#borderWidth").val($(a).css("border"+b[c]+"width"));parent.$("#dialog-cssedit").find("#borderColor").val("");for(c=0;c<b.length;c++)null!=$(a).css("border"+b[c]+"color")&&
"none"!=$(a).css("border"+b[c]+"color")&&""!=$(a).css("border"+b[c]+"color")&&parent.$("#dialog-cssedit").find("#borderColor").val(convertRGBToHex($(a).css("border"+b[c]+"color")));parent.$("#dialog-cssedit").find("#fontName, #fontSize, #padding, #margin").change(function(){parent.$("#dialog-cssedit").find("#width").val("");parent.$("#dialog-cssedit").find("#height").val("")});parent.$("#dialog-cssedit").dialog("option","buttons",[{text:html_entity_decode(rsApply),click:function(){$(a).removeClass("ipe_repeater_item_hover");
$(a).find(".ipe_toolbar").find(".ipe_cssedit").removeClass("ui-state-hover");parent.$(this).dialog("close");$(a).css("font-family",parent.$("#dialog-cssedit").find("#fontName").val());$(a).css("font-size",parent.$("#dialog-cssedit").find("#fontSize").val());$(a).css("color",parent.$("#dialog-cssedit").find("#fontcolor").val());$(a).css("background-color",parent.$("#dialog-cssedit").find("#bgcolor").val());$(a).css("width",parent.$("#dialog-cssedit").find("#width").val());$(a).css("height",parent.$("#dialog-cssedit").find("#height").val());
$(a).css("padding",parent.$("#dialog-cssedit").find("#padding").val());$(a).css("margin",parent.$("#dialog-cssedit").find("#margin").val());$(a).css("border-style",parent.$("#dialog-cssedit").find("#borderStyle").val());$(a).css("border-width",parent.$("#dialog-cssedit").find("#borderWidth").val());$(a).css("border-color",parent.$("#dialog-cssedit").find("#borderColor").val());parent.Modified=!0}},{text:rsCancel,click:function(){$(a).removeClass("ipe_repeater_item_hover");$(a).find(".ipe_toolbar").find(".ipe_cssedit").removeClass("ui-state-hover");
parent.$(this).dialog("close")}}])}
function PageBodyPropertiesEditor(){$("#no_template_loaded").remove();var a=$("body");parent.$("#dialog-pagebodyproperties").dialog("destroy");parent.$("#dialog-pagebodyproperties").dialog({resizable:!1,modal:!0,width:600,closeOnEscape:!1,close:function(){parent.CloseColorPicker()}});parent.$("#dialog-pagebodyproperties").find("#bodybgcolor").val(convertRGBToHex($(a).css("background-color")));var b=["","-top","-left","-right","-bottom"];parent.$("#dialog-pagebodyproperties").find("#bodypadding").val("");for(var c=
0;c<b.length;c++)if(null!=$(a).css("padding"+b[c])&&"none"!=$(a).css("padding"+b[c])&&""!=$(a).css("padding"+b[c])){parent.$("#dialog-pagebodyproperties").find("#bodypadding").val($(a).css("padding"+b[c]));break}parent.$("#dialog-pagebodyproperties").find("#bodymargin").val("");for(c=0;c<b.length;c++)if(null!=$(a).css("margin"+b[c])&&"none"!=$(a).css("margin"+b[c])&&""!=$(a).css("margin"+b[c])){parent.$("#dialog-pagebodyproperties").find("#bodymargin").val($(a).css("margin"+b[c]));break}parent.$("#dialog-pagebodyproperties").find("#bodyfontcolor").val(convertRGBToHex($(a).css("color")));
parent.$("#dialog-pagebodyproperties").find("#bodyfontName").val($(a).css("font-family"));parent.$("#dialog-pagebodyproperties").find("#bodyfontSize").val($(a).css("font-size"));$("a").css("color")?parent.$("#dialog-pagebodyproperties").find("#bodylinkcolor").val(convertRGBToHex($("a").css("color"))):parent.$("#dialog-pagebodyproperties").find("#bodylinkcolor").val(convertRGBToHex($("a:link").css("color")));$("a").css("text-decoration")?parent.$("#dialog-pagebodyproperties").find("#bodylinktextdecoration").val($("a").css("text-decoration")):
$("a:link").css("text-decoration")&&parent.$("#dialog-pagebodyproperties").find("#bodylinktextdecoration").val($("a:link").css("text-decoration"));parent.$("#dialog-pagebodyproperties").dialog("option","buttons",[{text:html_entity_decode(rsApply),click:function(){parent.$(this).dialog("close");$(a).css("background-color",parent.$("#dialog-pagebodyproperties").find("#bodybgcolor").val());$(a).css("padding",parent.$("#dialog-pagebodyproperties").find("#bodypadding").val());$(a).css("margin",parent.$("#dialog-pagebodyproperties").find("#bodymargin").val());
$(a).css("color",parent.$("#dialog-pagebodyproperties").find("#bodyfontcolor").val());$(a).css("font-family",parent.$("#dialog-pagebodyproperties").find("#bodyfontName").val());$(a).css("font-size",parent.$("#dialog-pagebodyproperties").find("#bodyfontSize").val());$("a").css("color",parent.$("#dialog-pagebodyproperties").find("#bodylinkcolor").val());$("a").css("text-decoration",parent.$("#dialog-pagebodyproperties").find("#bodylinktextdecoration").val());$("a:link").css("color",parent.$("#dialog-pagebodyproperties").find("#bodylinkcolor").val());
$("a:link").css("text-decoration",parent.$("#dialog-pagebodyproperties").find("#bodylinktextdecoration").val());parent.Modified=!0}},{text:rsCancel,click:function(){parent.$(this).dialog("close")}}])}function RemoveDoubleSpacesInSingleLine(a){return null==a?"":a.replace(/\n/g," ").replace(/\t/g,"").replace(/ +/g," ")}
function utf8_encode(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b}
function utf8_decode(a){for(var b="",c=0,d=c1=c2=0;c<a.length;)d=a.charCodeAt(c),128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(c2=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|c2&63),c+=2):(c2=a.charCodeAt(c+1),c3=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),c+=3);return b}function html_entity_decode(a){var b=parent.document.createElement("textarea");b.innerHTML=a;return b.value}
function convertRGBToHex(a){return null==a?"":0>a.indexOf("rgba")?a.replace(/(?:rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\))/gi,function(a,c,d,e){c=parseInt(c,10).toString(16);d=parseInt(d,10).toString(16);e=parseInt(e,10).toString(16);a=[c,d,e];for(c=0;c<a.length;c++)a[c]=String("0"+a[c]).slice(-2);return"#"+a.join("")}):a.replace(/(?:rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\))/gi,function(a,c,d,e,g){c=parseInt(c,10).toString(16);d=parseInt(d,10).toString(16);e=parseInt(e,10).toString(16);
a=[c,d,e];for(var f=0;f<a.length;f++)a[f]=String("0"+a[f]).slice(-2);return 0==g&&0==c&&0==d&&0==e?"transparent":"#"+a.join("")})}"function"!==typeof String.prototype.trim&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/,"")});